version: '2'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mc'
      # You can use whatever password you like
      MYSQL_PASSWORD: '22jMUELnnzRkZTta'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'z3kA6A78mX8E5YGa'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
    volumes:
      - ./data/mysqldb:/var/lib/mysql

  mongodb:
    image: bitnami/mongodb:4.0
    restart: always
    ports:
      - "27017:27017"
    hostname: mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=my_database
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
    volumes:
      - ./data/mongodb/:/bitnami/mongodb

  redis:
    image: 'bitnami/redis:5.0'
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/bitnami/redis/data

  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    restart: always
    environment:
      - RABBITMQ_USERNAME=mc
      - RABBITMQ_PASSWORD=123123
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - ./data/rabbitmq:/bitnami
